spring.application.name=Back-P1

spring.datasource.url=jdbc:postgresql://ep-hidden-bread-amqf036d-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_q6YhrjUQn7ia
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update